/* Shared style objects for use across components */
/* These replace inline style objects for better maintainability */

export const colors = {
  bg: '#0d1117',
  surface: '#161b22',
  surfaceHover: '#21262d',
  primary: '#58a6ff',
  primaryHover: '#79b8ff',
  success: '#3fb950',
  warning: '#d29922',
  danger: '#f85149',
  textPrimary: '#f0f6fc',
  textSecondary: '#8b949e',
  border: '#30363d',
};

export const layout = {
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '64px',
    backgroundColor: colors.surface,
    borderBottom: `1px solid ${colors.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    zIndex: 1000,
  },
  mainContent: {
    padding: '0 24px 24px 24px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  filterBar: {
    display: 'flex',
    gap: '16px',
    padding: '80px 24px 24px 24px',
    flexWrap: 'wrap',
    alignItems: 'center',
    backgroundColor: colors.bg,
  },
};

export const cards = {
  project: {
    backgroundColor: colors.surface,
    borderRadius: '8px',
    overflow: 'hidden',
    border: `1px solid ${colors.border}`,
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
    transition: 'transform 0.25s ease, background-color 0.25s ease, box-shadow 0.25s ease',
    cursor: 'default',
    position: 'relative',
  },
  projectHover: {
    transform: 'translateY(-4px)',
    backgroundColor: colors.surfaceHover,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '20px',
  },
  imageContainer: {
    height: '200px',
    width: '100%',
    overflow: 'hidden',
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.3s ease',
  },
  content: {
    padding: '16px',
  },
  title: {
    marginBottom: '8px',
    fontWeight: 'bold',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  description: {
    color: colors.textSecondary,
    fontSize: '12px',
    marginBottom: '12px',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  tagContainer: {
    display: 'flex',
    gap: '8px',
    marginBottom: '12px',
    flexWrap: 'wrap',
  },
  tag: (bgColor) => ({
    backgroundColor: bgColor,
    color: 'white',
    fontSize: '10px',
    padding: '2px 8px',
    borderRadius: '12px',
    fontWeight: 'bold',
  }),
  tagMuted: (textColor) => ({
    backgroundColor: colors.border,
    color: textColor || colors.textSecondary,
    fontSize: '10px',
    padding: '2px 8px',
    borderRadius: '12px',
  }),
  budgetRow: {
    marginBottom: '12px',
    fontSize: '13px',
    fontWeight: 'bold',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  progressBar: {
    flex: 1,
    height: '8px',
    backgroundColor: colors.border,
    borderRadius: '4px',
    overflow: 'hidden',
  },
  progressFill: (percentage) => ({
    width: `${percentage}%`,
    height: '100%',
    backgroundColor: colors.primary,
    transition: 'width 0.3s ease',
  }),
};

export const buttons = {
  primary: {
    backgroundColor: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    padding: '8px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontWeight: 'bold',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.15s ease',
  },
  secondary: {
    backgroundColor: 'transparent',
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px 16px',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, border-color 0.2s ease',
  },
  ghost: {
    backgroundColor: 'transparent',
    color: colors.textSecondary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px 16px',
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, color 0.2s ease',
  },
  icon: (hoverColor) => ({
    backgroundColor: 'rgba(0,0,0,0.6)',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    padding: '4px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.2s ease, transform 0.15s ease',
    hoverColor,
  }),
};

export const modal = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    backdropFilter: 'blur(4px)',
  },
  overlayDark: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3000,
    backdropFilter: 'blur(8px)',
  },
  container: {
    backgroundColor: colors.surface,
    width: '600px',
    maxHeight: '90vh',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  containerWide: {
    backgroundColor: colors.surface,
    width: '90%',
    maxWidth: '1000px',
    maxHeight: '90vh',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  header: {
    padding: '20px',
    borderBottom: `1px solid ${colors.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerHighlight: {
    padding: '20px',
    borderBottom: `1px solid ${colors.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surfaceHover,
  },
  body: {
    padding: '20px',
    overflowY: 'auto',
  },
  bodyGrid: {
    padding: '24px',
    overflowY: 'auto',
    display: 'grid',
    gridTemplateColumns: '1fr 2fr',
    gap: '24px',
  },
  formGrid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginBottom: '16px',
  },
  formGrid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '16px',
    marginBottom: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  label: {
    fontSize: '12px',
    color: colors.textSecondary,
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
  },
  closeButton: {
    background: 'none',
    border: 'none',
    color: colors.textSecondary,
    cursor: 'pointer',
    padding: '4px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'color 0.2s ease, background-color 0.2s ease',
  },
  input: {
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  textarea: {
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px',
    resize: 'vertical',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  select: {
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px',
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
};

export const form = {
  input: {
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  textarea: {
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px',
    height: '80px',
    resize: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  select: {
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    padding: '8px',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    cursor: 'pointer',
  },
  searchWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  searchInput: {
    padding: '8px 8px 8px 32px',
    width: '100%',
    fontFamily: 'inherit',
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, padding-left 0.2s ease',
  },
  uploadZone: {
    border: `2px dashed ${colors.border}`,
    borderRadius: '6px',
    padding: '30px',
    textAlign: 'center',
    color: colors.textSecondary,
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, background-color 0.2s ease, color 0.2s ease',
  },
};

export const subCountyHeading = {
  paddingTop: '0',
  paddingRight: '16px',
  paddingBottom: '0',
  paddingLeft: '12px',
  marginBottom: '16px',
  color: colors.primary,
  borderLeft: `4px solid ${colors.primary}`,
};

export const emptyState = {
  textAlign: 'center',
  padding: '60px',
  color: colors.textSecondary,
};

export const getStatusColor = (status) => {
  switch (status) {
    case 'Completed': return colors.success;
    case 'Ongoing': return colors.warning;
    case 'On Hold': return colors.danger;
    default: return colors.textSecondary;
  }
};
